name: Bike Point Ingestion

on:
  schedule:
  #EVERY 5 MINUTES
    - cron: '*/50 * * * *' 
  #ALLOW THE WORKFLOW TO RUN MANUALLY
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: bike point environment DES4
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.10'
      - name: Install packages
        run: pip install -r requirements.txt
  
      - name: run the python script
        env:
          MAILCHIMP_API_KEY: ${{secrets.MAILCHIMP_API_KEY}}
          MAILCHIMP_SERVER_PREFIX: ${{secrets.MAILCHIMP_SERVER_PREFIX}}
          AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
          AWS_ACCESS_SECRET_KEY: ${{secrets.AWS_ACCESS_SECRET_KEY}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
          SUMMARY_FILE_NAME: ${{secrets.SUMMARY_FILE_NAME}}
        run: python Extract.py
          
